// Package go_spipedmobile is an autogenerated binder stub for package spipedmobile.
//
// File is generated by gobind. Do not edit.
package go_spipedmobile

import (
	"code.google.com/p/go.mobile/bind/seq"
	"github.com/howeyc/spipedmobile"
)

func proxy_Start(out, in *seq.Buffer) {
	spipedmobile.Start()
}

func init() {
	seq.Register("spipedmobile", 1, proxy_Start)
}
