// Java Package spipedmobile is a proxy for talking to a Go program.
//
// File is generated by gobind. Do not edit.
package go.spipedmobile;

import go.Seq;

public abstract class Spipedmobile {
    private Spipedmobile() {} // uninstantiable
    
    public static void Start() {
        go.Seq _in = new go.Seq();
        go.Seq _out = new go.Seq();
        Seq.send(DESCRIPTOR, CALL_Start, _in, _out);
    }
    
    private static final int CALL_Start = 1;
    private static final String DESCRIPTOR = "spipedmobile";
}
